import type { Transaction } from '../types';

const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    title: 'Saudi Electricity Company',
    subTitle: 'SEC Utility Bill Payment',
    amount: 1420.50,
    type: 'sent',
    category: 'Utilities & Bills',
    date: 'TODAY',
    timestamp: new Date(),
    utr: 'UTR984729104821',
    avatarInitials: 'SE',
  },
  {
    id: 'tx-2',
    title: 'Tamimi Markets',
    subTitle: 'Supermarket & Groceries',
    amount: 385.25,
    type: 'sent',
    category: 'Groceries & Shopping',
    date: 'TODAY',
    timestamp: new Date(Date.now() - 3600000),
    utr: 'UTR192847291024',
    avatarInitials: 'TM',
  },
  {
    id: 'tx-3',
    title: 'AlBaik Restaurant',
    subTitle: 'Food & Dining',
    amount: 68.0,
    type: 'sent',
    category: 'Food & Dining',
    date: 'TODAY',
    timestamp: new Date(Date.now() - 7200000),
    utr: 'UTR384910294812',
    avatarInitials: 'AB',
  },
  {
    id: 'tx-4',
    title: 'Tariq Al-Harbi',
    subTitle: 'Instant Transfer',
    amount: 250.0,
    type: 'sent',
    category: 'Transfers & Split',
    date: 'TODAY',
    timestamp: new Date(Date.now() - 10800000),
    utr: 'UTR784910294112',
    avatarInitials: 'TH',
  },
  {
    id: 'tx-5',
    title: 'Careem Rides',
    subTitle: 'Mobility & Travel',
    amount: 45.0,
    type: 'sent',
    category: 'Travel & Mobility',
    date: 'YESTERDAY',
    timestamp: new Date(Date.now() - 86400000),
    utr: 'UTR224910294812',
    avatarInitials: 'CR',
  },
  {
    id: 'tx-6',
    title: 'Sara Al-Mansoor',
    subTitle: 'Money Received',
    amount: 1500.0,
    type: 'received',
    category: 'Transfers & Split',
    date: 'YESTERDAY',
    timestamp: new Date(Date.now() - 90000000),
    utr: 'UTR998491029481',
    avatarInitials: 'SM',
  },
  {
    id: 'tx-7',
    title: 'Panda Retail Superstore',
    subTitle: 'Home & Pantry',
    amount: 195.50,
    type: 'sent',
    category: 'Groceries & Shopping',
    date: '3 DAYS AGO',
    timestamp: new Date(Date.now() - 259200000),
    utr: 'UTR554910294819',
    avatarInitials: 'PR',
  },
  {
    id: 'tx-8',
    title: 'National Water Company',
    subTitle: 'NWC Water Bill',
    amount: 120.0,
    type: 'sent',
    category: 'Utilities & Bills',
    date: '5 DAYS AGO',
    timestamp: new Date(Date.now() - 432000000),
    utr: 'UTR884910294123',
    avatarInitials: 'NW',
  },
];

export const transactionService = {
  async getInitialTransactions(): Promise<Transaction[]> {
    return [...INITIAL_TRANSACTIONS];
  },
};
